version: 2
mergeable:
  - when: pull_request.opened
    name: "Label notice (QoL for PR filtering)"
    validate:
      - do: label
        must_include:
          regex: bug|enhancement|documentation
    fail:
      - do: comment
        payload:
          body:
            - Be sure to label this PR accordingly with at least `bug`, `enhancement`, or `documentation`
  - when: pull_request.opened
    name: "Branch naming convention check (Jira ticket prefix)"
    validate:
      - do: headRef
        must_include:
          regex: '^(feature|hotfix|bugfix)\/([A-Za-z])+-\d.+$'
    fail:
      - do: comment
        payload:
          body: >
            <h2>Your branch doesn't adhere to the branch naming convention as described in the
            SDLC <a href=https://docs.google.com/document/d/13DBQuZYshTm2YwKORAwWGIEHdhcjVeivTVT-zaxaF70/edit>doc</a>.</h2>
  - when: pull_request.opened
    name: "Commit naming convention check (Jira ticket prefix)"
    validate:
      - do: headRef
        must_include:
          regex: '^([A-Za-z])+-\d.+$'
    fail:
      - do: comment
        payload:
          body: >
            :warning:
            <h2> Jira ticket IDs missing in commits!</h2>
            <h3>Your commit doesn't adhere to the commit naming convention</h3>
            <ul>
              <li>as described in the SDLC <a href=https://docs.google.com/document/d/13DBQuZYshTm2YwKORAwWGIEHdhcjVeivTVT-zaxaF70/edit>doc</a>.</li>
              <li>prefix each commit with relevant Jira ticket you can rebase your commit messages and force push to fix this</li>
            </ul>
  - when: pull_request.*, pull_request_review.*
    name: "Request for review if not a draft"
    validate:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    pass:
      - do: request_review
        teams: ['Android']
